/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>

#define PLUGIN "The bomb has been planted"
#define VERSION "0.1"
#define AUTHOR "Inferno"

new const sound[]="misc/bp.wav"

public plugin_init()
{
register_plugin(PLUGIN, VERSION, AUTHOR)
}

public bomb_planted()
{
client_cmd(0, "stopsound")
client_cmd(0,"spk %s",sound)
}

public plugin_precache()
{
precache_sound(sound)
}